### ISSUE TITLE
Does window.performance.memory === window.performance.memory hold?

### ISSUE THREAD

**Issue by domenic** [WICG/performance-memory#2]
This is an important thing to include in any spec.

The answer should be yes, if at all possible.

**Comment by erikchen** [comment]
window.performance === window.performance currently returns true on Chrome, but I expect this to be flaky [depends on bucketing and time-delay], and once tdresser removes those in https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/no00RdMnGio, I expect this to generally be false.

In general, I don't see how we can guarantee "window.performance.memory === window.performance.memory" while still producing dynamic results. Could you describe how this would normally be done?

**Comment by domenic** [comment]
You'd have the properties of window.performance.memory return new values, while still having the object keep its same identity (never recreating a new MemoryInfo object).

**Comment by erikchen** [comment]
Ah I see, thanks.

**Comment by erikchen** [comment]
Done in https://github.com/erikchen/performance-memory/commit/506fbe138e8572227e673652bda8747491ac3e3a.
