### ISSUE TITLE
The specification uses a dictionary, but Chrome does not

### ISSUE THREAD

**Issue by domenic** [WICG/performance-memory#3]
In Chrome, the IDL appears to use a MemoryInfo interface: https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/timing/MemoryInfo.idl?q=MemoryInfo.idl&sq=package:chromium&l=1

A dictionary has significantly different semantics, e.g. you can modify the properties of dictionaries, and they use data properties instead of the getters of an interface.

**Comment by erikchen** [comment]
That was a mistake. Switched to MemoryInfo interface in https://github.com/erikchen/performance-memory/commit/38f0b46ad4fc04de89660ddb5c376cc5b9d4ab95.
