### ISSUE TITLE
This specification should have valid IDL

### ISSUE THREAD

**Issue by domenic** [WICG/performance-memory#4]
https://github.com/erikchen/performance-memory/blob/master/explainer.md#proposed-api does not contain valid IDL, but appears to gesture toward it by using the term "dictionary" (see #3).

**Comment by erikchen** [comment]
Fixed in https://github.com/erikchen/performance-memory/commit/38f0b46ad4fc04de89660ddb5c376cc5b9d4ab95

**Comment by domenic** [comment]
Probably also need to specify that `navigator.memory` returns a `MemoryInfo`? Using `[SameObject]` to ensure #2.

**Comment by erikchen** [comment]
Ah, you mean performance.memory? I updated the IDL to

"""
partial interface Performance {
  [SameObject, Measure] readonly attribute MemoryInfo memory;
}

// All values will be |null| if there are multiple top-level frames being hosted
// by the same process. Once site-isolation is enabled, this will never be the
// case.
interface MemoryInfo {
  // All private memory being used by the process hosting the site.
  readonly attribute unsigned long? privateMemoryFootprint;

  // Sum of size of all JS-related entities in the process hosting the site.
  // Includes objects, functions, closures, array buffers, etc.
  readonly attribute unsigned long? usedJSHeapSize;

  // All memory used by the JS heap in the process hosting the site.
  // Includes everything from usedJSHeapSize, and also fragmentation.
  readonly attribute unsigned long? totalJSHeapSize;
}
"""

**Comment by domenic** [comment]
Looks good :). Probably just want to remove the `, Measure` part since that's a Blink-specific use counter-related IDL attribute.

**Comment by erikchen** [comment]
Done, thanks for all the help!
