### ISSUE TITLE
In Chrome this is [NoInterfaceObject]. Should it be?

### ISSUE THREAD

**Issue by domenic** [WICG/performance-memory#5]
[NoInterfaceObject] is generally deprecated and should be avoided. But, maybe this is a legacy use case where we'd want to keep it.

**Comment by erikchen** [comment]
I'm no expert here, but my reading of https://heycam.github.io/webidl/#NoInterfaceObject suggests that there is no reason we need to keep NoInterfaceObject. I have refrained from adding it to the IDL.
